language: scala

scala:
  - 2.12.8

# These directories are cached at the end of the build
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"

before_cache:
  # These directories are cached at the end of the build
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

# credentials for publishing releases to Sonatype
env:
  global:
    - secure: dllL1w+pZT6yTBYwy5hX07t8r0JL5Cqer6YgYnXJ+q3OhSGUs7ul2fDUiqVxGIgUpTij1cGwBmoJOTbRk2V/be4+3Ua4ZNrAxjNF2ehqUcV5KdC3ufTTTXX0ZoL9MqEIb+GKzKtPqbzR4uly/5q5NbV7J1GeZRhummnx87POl6yH4kmXTpahig7vvnwN5dLanMshRb2Z8tO8kF4SnC31QuNBDQLnS89PEajHQu+LRAJloYvcikm+NeUj79m64CYg9JZdrHvZpIYKOMY1twT+lYoerqzG+asiNE1WrDs/We1RFVgcrKLpEThcvuIxuuPKhu24+0KteAX+7z/ulT0lndyBRfuuDjHV844LrNbjhnTB64V1uF7aEdaEZRLTsFQnFZqzpoqYqxzgfow9LN/kU5CMJX1R4wwf3YgR1VC9ZfjZnu0Pbt24g48I+72ZDNk3oRZoPsN9AtovwdZcg7TgU/iPcHNKSNhEZRP6ryhv/9aX3URLkfhnDaJmTXAnC3YCYt5cGo0FBUHARA+AHcas14Dx95bFSbH7EBivb2LiDmi44goRCWR4p+vNSBJ6Ak1NZz/+paai0pXDG6S/VdqwGSmmfjn7m9H3L5c8X5xNich9qtZbWz0fj2baZGq/doA8KE91JCzX11p/9fKNzbVivQZdsw3C3ZWDjkMZM+hl++0=
    - secure: clR0WPfxY4j5M6GSuS3lvFqg+6g+EN62xmSOVFnCGVTHx6tD3PFJzCtodv+ZFORAK96r9Xrihpw8TCrXGb7pM7z53lzqfj5GnHa+JZsi+rhlGnFQkxcc2d6EpsQMPQ1own1TS0cH7GCN5h7EuKOfIAW8yV3/507Ix3ugP4rp+gAXpFOE/FXvkUp3FFddHgmBUVWyJ+be660oejrzX0tmc4q3wmyWXFK7BOotnRFXWt8BFyW3/DljekJU06Yi+JAxdxeLlACNpL9giPJ8llONmDoNzJcpeIzMgG2u179tAXwGjvW1abcvyEmL2REjYuTdZtRbWz8lY7f5XG93m9snoBePnMmg/tYHFLE0iT2p9+NvLiFGhejXOeLZn+El8jqBpXpMCgouLzg1W2in3Yx9Xz1ENLS3QHU2Snsh/NG95XX/r5BQePOwdU7k0sOoyfs1iUNVZwBhcnRwp2/87hOndCcq9TXTg6lcx0e+nzM3TmqdHvz6fIRYvGS7gVI06rStzXAvf7gmx6ESPknyNIB8Ah8MRgjNAC33S7ZTYwq88Dn+hdH99opUYJJcDeZTk3m5pCYX5RBV/xRetrDm9WccZucVuWUu/fiflUSsMFIUkKBO4uMOFHtbYf0oqczcFFxKrmzaMd3fO+8X9bIyhAGp80d1oMNhYxUvDGMShgSsvGk=

